### ISSUE TITLE
请问这是那篇论文的实现？

### ISSUE THREAD

**Issue by gaozhen123456** [khamfroush-lab/Fed-MEC#1]
Is this the implementation of that paper?
Is this the implementation of that paper?

**Comment by Nchudson95** [comment]
This repo serves as a hub for several different papers from our group. Is there a specific paper you're referring to?

**Comment by gaozhen123456** [comment]
yes，paper is？



---原始邮件---
发件人: "Nathaniel ***@***.***&gt;
发送时间: 2021年8月2日(周一) 凌晨0:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [khamfroush-lab/Fed-MEC] 请问这是那篇论文的实现？ (#1)




 
This repo serves as a hub for several different papers from our group. Is there a specific paper you're referring to?

**Comment by Nchudson95** [comment]
_Which_ paper are you referring to?

**Comment by gaozhen123456** [comment]
which article does this code correspond to？



---原始邮件---
发件人: "Nathaniel ***@***.***&gt;
发送时间: 2021年8月2日(周一) 凌晨2:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [khamfroush-lab/Fed-MEC] 请问这是那篇论文的实现？ (#1)




 
Which paper are you referring to?

**Comment by gaozhen123456** [comment]
all paper 

Send out the name of the paper
Send out the name of the paper

**Comment by gaozhen123456** [comment]
Send out the name of the paper
Send out the name of the paper
Send out the name of the paper
Send out the name of the paper

**Comment by Nchudson95** [comment]
This [subdir](https://github.com/khamfroush-lab/Fed-MEC/tree/master/Distributed-Client-Selection-FL) in the repo contains code for the following published work:
https://ieeexplore.ieee.org/abstract/document/9500744
